services:
  jellyjams:
    image: jonasmore/jellyjams:latest
    container_name: jellyjams
    environment:
      # Default values are set here like ${VAR_NAME:-DEFAULT_VALUE}
      # in case they aren't provided in the .env file. If you use the
      # .env file, there is no need to change the default values.
      - PUID=${PUID:-1000} # Match with Jellyfin
      - PGID=${PGID:-1000} # Match with Jellyfin
      - JELLYFIN_URL=${JELLYFIN_URL:-http://jellyfin:8096}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - LOG_LEVEL=${JELLYJAMS_LOG_LEVEL:-DEBUG}
      - TRIGGER_LIBRARY_SCAN=${TRIGGER_LIBRARY_SCAN:-true}
      - ENABLE_WEB_UI=${ENABLE_WEB_UI:-true}
      - WEB_PORT=${WEB_PORT:-5000}
      - WEBUI_BASIC_AUTH_ENABLED=${WEBUI_BASIC_AUTH_ENABLED:-false}
      - WEBUI_BASIC_AUTH_USERNAME=${WEBUI_BASIC_AUTH_USERNAME:-admin}
      - WEBUI_BASIC_AUTH_PASSWORD=${WEBUI_BASIC_AUTH_PASSWORD:-admin}
      # Discord Notifications
      - DISCORD_WEBHOOK_ENABLED=${DISCORD_WEBHOOK_ENABLED}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - ${JELLYJAMS_DATA_DIR_HOST}:/data
      # Ready-only access to music directory for cover art generation
      - ${MUSIC_DIR_HOST}:${MUSIC_DIR_CONTAINER}:ro
      # Jellyfin playlists directory for playlist and art management
      - ${PLAYLIST_DIR_HOST}:/playlists
    ports:
      - "${WEB_PORT:-5000}:${WEB_PORT:-5000}"
    restart: unless-stopped
