version: '3.8'

services:
  jellyjams:
    build: .
    container_name: jellyjams
    environment:
      # Essential container settings (not configurable via web UI)
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - PLAYLIST_FOLDER=${PLAYLIST_FOLDER}
      - ENABLE_WEB_UI=${ENABLE_WEB_UI}
      - WEB_PORT=${WEB_PORT}
      # Default fallback values (web UI settings will override these)
      - LOG_LEVEL=${LOG_LEVEL}
      - GENERATION_INTERVAL=${GENERATION_INTERVAL}
      - MAX_TRACKS_PER_PLAYLIST=${MAX_TRACKS_PER_PLAYLIST}
      - MIN_TRACKS_PER_PLAYLIST=${MIN_TRACKS_PER_PLAYLIST}
      - EXCLUDED_GENRES=${EXCLUDED_GENRES}
      - SHUFFLE_TRACKS=${SHUFFLE_TRACKS}
      - PLAYLIST_TYPES=${PLAYLIST_TYPES}
    volumes:
      # Local directories for Docker Desktop (using named volumes to avoid path issues)
      - jellyjams_playlists:/app/playlists
      - jellyjams_logs:/app/logs
      - jellyjams_config:/app/config
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  jellyjams_playlists:
  jellyjams_logs:
  jellyjams_config:
