services:
  jellyjams:
    image: jonasmore/jellyjams:latest
    container_name: jellyjams
    environment:
      # Essential container settings (not configurable via web UI)
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - ENABLE_WEB_UI=${ENABLE_WEB_UI}
      - WEB_PORT=${WEB_PORT}
      # Default fallback values (web UI settings will override these)
      - LOG_LEVEL=${LOG_LEVEL}
      - GENERATION_INTERVAL=${GENERATION_INTERVAL}
      - MAX_TRACKS_PER_PLAYLIST=${MAX_TRACKS_PER_PLAYLIST}
      - MIN_TRACKS_PER_PLAYLIST=${MIN_TRACKS_PER_PLAYLIST}
      - EXCLUDED_GENRES=${EXCLUDED_GENRES}
      - SHUFFLE_TRACKS=${SHUFFLE_TRACKS}
      - PLAYLIST_TYPES=${PLAYLIST_TYPES}
      # Discovery playlist diversity controls
      - DISCOVERY_MAX_SONGS_PER_ALBUM=${DISCOVERY_MAX_SONGS_PER_ALBUM}
      - DISCOVERY_MAX_SONGS_PER_ARTIST=${DISCOVERY_MAX_SONGS_PER_ARTIST}
      # Trigger Jellyfin media library scan after playlist creation
      - TRIGGER_LIBRARY_SCAN=${TRIGGER_LIBRARY_SCAN}
      # Web UI Security (environment variables override web UI settings)
      - WEBUI_BASIC_AUTH_ENABLED=${WEBUI_BASIC_AUTH_ENABLED}
      - WEBUI_BASIC_AUTH_USERNAME=${WEBUI_BASIC_AUTH_USERNAME}
      - WEBUI_BASIC_AUTH_PASSWORD=${WEBUI_BASIC_AUTH_PASSWORD}
      # Discord Notifications
      - DISCORD_WEBHOOK_ENABLED=${DISCORD_WEBHOOK_ENABLED}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      # Bind appdata directory for JellyJams (config, logs, cover)
      - /mnt/user/appdata/jellyjams:/data
      # Jellyfin playlists directory for playlist and art management
      - ${PLAYLIST_DIR_HOST}:/playlists
      # Read-only access to music directory for cover art generation
      - ${MUSIC_DIR_HOST}:${MUSIC_DIR_CONTAINER}:ro
    ports:
      - "${WEB_PORT:-5000}:${WEB_PORT:-5000}"
    restart: unless-stopped
