services:
  jellyjams:
    image: jonasmore/jellyjams:latest
    container_name: jellyjams
    environment:
      # Essential container settings (not configurable via web UI)
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - PLAYLIST_FOLDER=${PLAYLIST_FOLDER}
      - ENABLE_WEB_UI=${ENABLE_WEB_UI}
      - WEB_PORT=${WEB_PORT}
      # Default fallback values (web UI settings will override these)
      - LOG_LEVEL=${LOG_LEVEL}
      - GENERATION_INTERVAL=${GENERATION_INTERVAL}
      - MAX_TRACKS_PER_PLAYLIST=${MAX_TRACKS_PER_PLAYLIST}
      - MIN_TRACKS_PER_PLAYLIST=${MIN_TRACKS_PER_PLAYLIST}
      - EXCLUDED_GENRES=${EXCLUDED_GENRES}
      - SHUFFLE_TRACKS=${SHUFFLE_TRACKS}
      - PLAYLIST_TYPES=${PLAYLIST_TYPES}
      # Web UI Security (environment variables override web UI settings)
      - WEBUI_BASIC_AUTH_ENABLED=${WEBUI_BASIC_AUTH_ENABLED}
      - WEBUI_BASIC_AUTH_USERNAME=${WEBUI_BASIC_AUTH_USERNAME}
      - WEBUI_BASIC_AUTH_PASSWORD=${WEBUI_BASIC_AUTH_PASSWORD}
      # Discord Notifications
      - DISCORD_WEBHOOK_ENABLED=${DISCORD_WEBHOOK_ENABLED}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      # Local directories for Docker Desktop (using named volumes to avoid path issues)
      - jellyjams_playlists:/app/playlists
      - jellyjams_logs:/app/logs
      - jellyjams_config:/app/config
      - jellyjams_cover:/app/cover
      # Music directory for cover art generation (adjust path for your system)
      - /mnt/user/media/data/music:/mnt/user/media/data/music:ro
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  jellyjams_playlists:
  jellyjams_logs:
  jellyjams_config:
  jellyjams_cover:
